'use strict';
/**
 * bot-runner.js - QR Code method
  * Pushes status.json to bot-data branch using git worktree.
   * Handles 408/connection failures by clearing auth and doing fresh QR.
    */
    const path = require('path');
    const fs   = require('fs');
    const { execSync } = require('child_process');
    const QRCode = require('qrcode');
    const { startServer, storeMessage, setSocket } = require('./server');
    const {
      default: makeWASocket,
        useMultiFileAuthState,
          DisconnectReason,
            fetchLatestBaileysVersion,
              makeCacheableSignalKeyStore,
                Browsers,
                } = require('@whiskeysockets/baileys');
                const { Boom } = require('@hapi/boom');
                const pino = require('pino');
                
                const AUTH_DIR   = path.join(process.cwd(), 'auth_info');
                const WORKTREE_DIR = path.join(process.cwd(), '.bot-data-wt');
                
                // ── git worktree helpers ──────────────────────────────────────────────────────
                function setupWorktree() {
                  try {
                      execSync('git config user.email "bot@github.com"', { stdio: 'pipe' });
                          execSync('git config user.name "WhatsApp Bot"', { stdio: 'pipe' });
                              let branchExists = false;
                                  try {
                                        const out = execSync('git ls-remote --heads origin bot-data', { stdio: 'pipe' }).toString();
                                              branchExists = out.includes('bot-data');
                                                  } catch(_) {}
                                                      if (!branchExists) {
                                                            console.log('[git] Creating bot-data branch...');
                                                                  execSync('git fetch origin main', { stdio: 'pipe' });
                                                                        execSync('git branch bot-data origin/main', { stdio: 'pipe' });
                                                                              execSync('git push origin bot-data', { stdio: 'pipe' });
                                                                                  }
                                                                                      if (fs.existsSync(WORKTREE_DIR)) {
                                                                                            try { execSync('git worktree remove --force ' + WORKTREE_DIR, { stdio: 'pipe' }); } catch(_) {}
                                                                                                }
                                                                                                    execSync('git fetch origin bot-data:bot-data 2>/dev/null || git fetch origin bot-data', { stdio: 'pipe' });
                                                                                                        execSync('git worktree add ' + WORKTREE_DIR + ' bot-data', { stdio: 'pipe' });
                                                                                                            console.log('[git] bot-data worktree ready');
                                                                                                                return true;
                                                                                                                  } catch(e) {
                                                                                                                      console.error('[git] Worktree setup failed:', e.message.slice(0, 120));
                                                                                                                          return false;
                                                                                                                            }
                                                                                                                            }
                                                                                                                            
                                                                                                                            let worktreeReady = false;
                                                                                                                            
                                                                                                                            function pushStatusToBotData(statusJson) {
                                                                                                                              if (!worktreeReady) { worktreeReady = setupWorktree(); }
                                                                                                                                if (worktreeReady && fs.existsSync(WORKTREE_DIR)) {
                                                                                                                                    try {
                                                                                                                                          fs.writeFileSync(path.join(WORKTREE_DIR, 'status.json'), statusJson);
                                                                                                                                                execSync('git -C ' + WORKTREE_DIR + ' add status.json', { stdio: 'pipe' });
                                                                                                                                                      try {
                                                                                                                                                              execSync('git -C ' + WORKTREE_DIR + ' commit -m "chore: update tunnel URL [skip ci]"', { stdio: 'pipe' });
                                                                                                                                                                      execSync('git -C ' + WORKTREE_DIR + ' push origin bot-data', { stdio: 'pipe' });
                                                                                                                                                                              console.log('[git] Pushed status to bot-data');
                                                                                                                                                                                    } catch(_) { console.log('[git] Nothing changed in status.json'); }
                                                                                                                                                                                          return;
                                                                                                                                                                                              } catch(e) { console.error('[git] Worktree push failed:', e.message.slice(0, 120)); }
                                                                                                                                                                                                }
                                                                                                                                                                                                  // Fallback to main
                                                                                                                                                                                                    try {
                                                                                                                                                                                                        fs.writeFileSync('status.json', statusJson);
                                                                                                                                                                                                            execSync('git add status.json', { stdio: 'pipe' });
                                                                                                                                                                                                                try {
                                                                                                                                                                                                                      execSync('git commit -m "chore: update tunnel URL [skip ci]"', { stdio: 'pipe' });
                                                                                                                                                                                                                            execSync('git push', { stdio: 'pipe' });
                                                                                                                                                                                                                                  console.log('[git] Fallback: pushed to main');
                                                                                                                                                                                                                                      } catch(_) {}
                                                                                                                                                                                                                                        } catch(e) { console.error('[git] Fallback push failed:', e.message.slice(0, 80)); }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        function getTunnelUrl() {
                                                                                                                                                                                                                                          const wtFile    = path.join(WORKTREE_DIR, 'status.json');
                                                                                                                                                                                                                                            const localFile = 'status.json';
                                                                                                                                                                                                                                              for (const f of [wtFile, localFile]) {
                                                                                                                                                                                                                                                  try { return JSON.parse(fs.readFileSync(f, 'utf8')).url || null; } catch(_) {}
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      return null;
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                      function writeStatus(data) {
                                                                                                                                                                                                                                                        const url = getTunnelUrl();
                                                                                                                                                                                                                                                          const payload = { url, ts: Math.floor(Date.now() / 1000), ...data };
                                                                                                                                                                                                                                                            const qrLen = data.qr ? Math.round(data.qr.length / 1024) + 'KB' : 'none';
                                                                                                                                                                                                                                                              console.log('[status] connected=' + data.connected + ' qr=' + qrLen);
                                                                                                                                                                                                                                                                pushStatusToBotData(JSON.stringify(payload, null, 2));
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                function clearAuth() {
                                                                                                                                                                                                                                                                  try { fs.rmSync(AUTH_DIR, { recursive: true, force: true }); } catch(_) {}
                                                                                                                                                                                                                                                                    try { fs.mkdirSync(AUTH_DIR, { recursive: true }); } catch(_) {}
                                                                                                                                                                                                                                                                      console.log('[runner] Auth cleared for fresh QR');
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                      // ── Main ──────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                      async function main() {
                                                                                                                                                                                                                                                                        await startServer();
                                                                                                                                                                                                                                                                          console.log('[runner] Web server started on port 3000');
                                                                                                                                                                                                                                                                            await startBot(false);
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            async function startBot(isRetry) {
                                                                                                                                                                                                                                                                              fs.mkdirSync(AUTH_DIR, { recursive: true });
                                                                                                                                                                                                                                                                                const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);
                                                                                                                                                                                                                                                                                  const { version } = await fetchLatestBaileysVersion();
                                                                                                                                                                                                                                                                                    console.log('[runner] Baileys v' + version.join('.'));
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                      const logger = pino({ level: 'silent' });
                                                                                                                                                                                                                                                                                        const sock = makeWASocket({
                                                                                                                                                                                                                                                                                            version,
                                                                                                                                                                                                                                                                                                logger,
                                                                                                                                                                                                                                                                                                    auth: {
                                                                                                                                                                                                                                                                                                          creds: state.creds,
                                                                                                                                                                                                                                                                                                                keys: makeCacheableSignalKeyStore(state.keys, logger),
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                        browser: Browsers.ubuntu('Chrome'),
                                                                                                                                                                                                                                                                                                                            printQRInTerminal: true,
                                                                                                                                                                                                                                                                                                                                generateHighQualityLinkPreview: false,
                                                                                                                                                                                                                                                                                                                                    qrTimeout: 60000,
                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                        setSocket(sock);
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                          sock.ev.on('connection.update', async (update) => {
                                                                                                                                                                                                                                                                                                                                              const { connection, lastDisconnect, qr } = update;
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                  if (qr) {
                                                                                                                                                                                                                                                                                                                                                        console.log('[runner] QR received - generating base64...');
                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                      const qrDataUrl = await QRCode.toDataURL(qr, {
                                                                                                                                                                                                                                                                                                                                                                                width: 512,
                                                                                                                                                                                                                                                                                                                                                                                          margin: 4,
                                                                                                                                                                                                                                                                                                                                                                                                    errorCorrectionLevel: 'M',
                                                                                                                                                                                                                                                                                                                                                                                                              color: { dark: '#000000', light: '#ffffff' },
                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                              writeStatus({ connected: false, qr: qrDataUrl, error: null });
                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('[runner] QR generation failed:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (connection === 'close') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const statusCode = new Boom(lastDisconnect?.error)?.output?.statusCode;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('[runner] Connection closed, reason:', statusCode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writeStatus({ connected: false, qr: null, error: null });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (statusCode === DisconnectReason.loggedOut) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Explicitly logged out - clear auth and restart fresh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('[runner] Logged out - clearing auth, restarting in 5s...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          clearAuth();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(function() { startBot(false); }, 5000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (statusCode === 408 || statusCode === 503 || statusCode === 428) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 408 = QR scan timeout / connection failure during pairing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 428 = connection replaced
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 503 = service unavailable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Clear stale auth and wait longer before retrying
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('[runner] QR scan failed (' + statusCode + ') - clearing auth, retrying in 10s...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clearAuth();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(function() { startBot(false); }, 10000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (statusCode === 401) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Unauthorized - clear auth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('[runner] Auth failed (401) - clearing auth, retrying in 5s...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              clearAuth();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setTimeout(function() { startBot(false); }, 5000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Network or other transient error - reconnect without clearing auth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const delay = isRetry ? 15000 : 5000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('[runner] Reconnecting in ' + (delay/1000) + 's...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(function() { startBot(true); }, delay);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (connection === 'open') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('[runner] WhatsApp connected!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      writeStatus({ connected: true, qr: null, error: null });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sock.ev.on('creds.update', saveCreds);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sock.ev.on('messages.upsert', async ({ messages, type }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (const msg of messages) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!msg.message) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const jid  = msg.key.remoteJid || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const text = msg.message?.conversation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              || msg.message?.extendedTextMessage?.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      || msg.message?.imageMessage?.caption
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              || msg.message?.videoMessage?.caption
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      || '[Media/Other]';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const fromMe = msg.key.fromMe;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  storeMessage(jid, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: msg.key.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fromMe,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  timestamp: msg.messageTimestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pushName: msg.pushName || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!fromMe && type === 'notify') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('[msg] ' + jid + ': ' + text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          main().catch(function(err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('[runner] Fatal:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });